25 param
Qiskit/qiskit-metal pull request #399
Opened 2021-03-16 23:01 UTC by grace-harper-ibm

### What are the issues this pull addresses (issue numbers / links)?
25

### Did you add tests to cover your changes (yes/no)?
yes
### Did you update the documentation accordingly (yes/no)?
yes
### Did you read the CONTRIBUTING document (yes/no)?
yes
### Summary
Users can now create QComponents directly from the GUI

### Details and comments

2021-03-17 18:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=399) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-metal?pullRequest=399) it.</sub>

2021-03-17 19:50 UTC, priti-ashvin-shah-ibm commented on qiskit_metal/_gui/widgets/library_new_qcomponent/parameter_entry_window.py
> +            options = self.qcomp_class.get_template_options(self._design)
Nice

2021-03-17 20:32 UTC, priti-ashvin-shah-ibm commented
Observation: Presently, there is just one QComponent in module.  Just want to confirm we will not have multiple QComponents in within one module?

2021-03-17 20:39 UTC, priti-ashvin-shah-ibm commented
![image](https://user-images.githubusercontent.com/74020801/111535312-5beed400-873f-11eb-9ec6-b0d5af7f7fca.png)
Is this an easy change, or can I request for future issue to be added?

2021-03-17 21:46 UTC, priti-ashvin-shah-ibm approved these changes
Ran a notebook and added QComponents through GUI. Was able to work with both interactively. Really Great work.  !!!

Noticed on command line that every test in run_all_tests failed.  Seems to be reflected in CI also.

2021-03-18 11:05 UTC, JeremyDrysdale-ibm requested changes
Please merge in main, and fix the merge conflicts, then I'll review.

2021-03-18 15:44 UTC, JeremyDrysdale-ibm approved these changes
LGTM

2021-03-18 15:45 UTC, priti-ashvin-shah-ibm commented
Don't want to hold up the pr.  It can be a separate issue.
Is it possible to move the dividing bar?  Maybe user can “doc” the window when working on entering the data?

2021-03-18 15:50 UTC, priti-ashvin-shah-ibm approved these changes
I have made two requests.  If they are not quick fixes, please make them as new issues. Will approve.  This is a big, very nice feature.  Great job.

2021-03-18 15:50 UTC, JeremyDrysdale-ibm commented
> Don't want to hold up the pr. It can be a separate issue.
> Is it possible to move the dividing bar? Maybe user can “doc” the window when working on entering the data?

@priti-ashvin-shah-ibm Perhaps that's best as a separate issue.  This PR already contains a LOT of completed work.

2021-03-18 16:09 UTC, priti-ashvin-shah-ibm approved these changes

2021-03-18 16:56 UTC, JeremyDrysdale-ibm approved these changes
LGTM

2021-03-18 17:37 UTC, ThomasGM4 approved these changes
Looks good.
Still some discussion on how to best manage variable aspects (such as connection pads for qubits).

2021-03-18 18:17 UTC, merged