383 notebook reviews
Qiskit/qiskit-metal pull request #400
Opened 2021-03-17 05:35 UTC by ThomasGM4

### What are the issues this pull addresses (issue numbers / links)?

Closes #383 

### Did you add tests to cover your changes (yes/no)?

No

### Did you update the documentation accordingly (yes/no)?

Yes

### Did you read the CONTRIBUTING document (yes/no)?

### Summary

Notebook reviews and modifications
Added bib file
Made minor modifications to some different methods.

### Details and comments

Notebooks should be fully functional, small errors have been fixed.

Added a .bib file for citing of Metal. Link in FAQ pointing to said file to be later added (such as in https://qiskit.org/documentation/faq.html)

Some small changes to a few methods, mainly modifying default values to more design appropriate options. One changed the number of expected inputs, which may need an update to tests.

2021-03-17 10:06 UTC, JeremyDrysdale-ibm submitted a review, later dismissed
Not worth holding the PR up for, but I have one question about the `.bib` year noted below.

2021-03-17 14:12 UTC, priti-ashvin-shah-ibm commented on tutorials/6 Analysis/S Param Simulation.ipynb
>      "First parameter: List of components to render (empty list if rendering whole Metal design) <br>\n",
Above, regarding cell for open_ansys(), suggest alternate text.

Skip the next cell if Ansys is already open and with a project loaded.

in bold:
**Wait for Ansys to open up completely before proceeding to the next cell.**

2021-03-17 18:11 UTC, ThomasGM4 commented on Qiskit_Metal.bib
> +year = {2020},
That is a good question. Not sure what the rule is for open source software, when first mentioned publicly? When it becomes open source? When it hits version 1.0?

2021-03-17 18:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=400) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=400) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-metal?pullRequest=400) it.</sub>

2021-03-17 18:47 UTC, ThomasGM4 commented on tutorials/6 Analysis/Analyzing a transmon.ipynb
> -   "id": "southeast-stock",
Didn't quite follow what you meant for this.

2021-03-17 19:47 UTC, priti-ashvin-shah-ibm commented on tutorials/6 Analysis/Analyzing a transmon.ipynb
> -   "id": "southeast-stock",
"Note that the design size extends from the origin into the first quadrant."

The above text is written below.

2021-03-18 11:52 UTC, JeremyDrysdale-ibm submitted a review, later dismissed
LGTM

2021-03-18 16:55 UTC, grace-harper-ibm commented
Is `https://github.com/Qiskit/qiskit-metal/blob/main/Qiskit_Metal.bib` supposed to be an accessible website from the browser? I was unable to access it

2021-03-18 17:45 UTC, priti-ashvin-shah-ibm approved these changes
LGTM

2021-03-18 18:22 UTC, JeremyDrysdale-ibm submitted a review, later dismissed
LGTM

2021-03-18 18:33 UTC, grace-harper-ibm requested changes

2021-03-18 18:48 UTC, priti-ashvin-shah-ibm commented on README.md
> +Qiskit Metal is the work of [many people](https://github.com/Qiskit/qiskit-metal/pulse/monthly) who contribute to the project at different levels. Metal was conceived and developed by [Zlatko Minev](
I checked also, I was not able to access https://github.com/Qiskit/qiskit-metal/blob/main/Qiskit_Metal.bib.

2021-03-18 19:40 UTC, ThomasGM4 commented on tutorials/6 Analysis/Analyzing a transmon.ipynb
>   "cells": [
Hmmm, I am now also getting that error.

2021-03-18 19:41 UTC, ThomasGM4 commented on README.md
> +Qiskit Metal is the work of [many people](https://github.com/Qiskit/qiskit-metal/pulse/monthly) who contribute to the project at different levels. Metal was conceived and developed by [Zlatko Minev](
Because it is pointing at main, which this branch has not yet merged into.

2021-03-18 20:24 UTC, priti-ashvin-shah-ibm approved these changes
LGTM

2021-03-18 20:55 UTC, grace-harper-ibm approved these changes
LGTM

2021-03-18 21:05 UTC, JeremyDrysdale-ibm approved these changes
LGTM

2021-03-18 21:06 UTC, merged