Create transmon_analytics.py
Qiskit/qiskit-metal pull request #438
Opened 2021-03-23 18:51 UTC by nalanzil

This file plots the transmon eigenvalues as a function of offset charge (ng) for a given energy level (m).

### What are the issues this pull addresses (issue numbers / links)?

This issue (partially) addresses issue #218 . However, a numerical method which allows one to use non-integer indices in the calculation of Mathieu characteristic values would be a nice improvement. 

### Did you add tests to cover your changes (yes/no)?

Yes. 

### Did you update the documentation accordingly (yes/no)?

No

### Did you read the CONTRIBUTING document (yes/no)?

Yes

### Summary

I added a file "transmon_analytics" which creates the plots of transmon eigenvalues as a function of offset charge for various energy levels. This addresses issue #218 

### Details and comments

Same as above.

2021-03-23 18:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=438) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=438) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-metal?pullRequest=438) it.</sub>

2021-03-26 11:38 UTC, JeremyDrysdale-ibm requested changes
I noticed that the plot is created automatically when the module in imported, can you move that to a function? I can think of instances in which someone wouldn't want the plot to be created automatically -- like during testing, or docs generation.

2021-03-26 12:21 UTC, nalanzil commented
Included a separate function to create the plot so that it's not generated automatically.

2021-03-26 13:27 UTC, JeremyDrysdale-ibm approved these changes
LGTM

2021-03-28 17:37 UTC, merged