Qlibrary reorg
Qiskit/qiskit-metal pull request #483
Opened 2021-04-21 15:16 UTC by marcolincs

### What are the issues this pull addresses (issue numbers / links)?
Closes #375

### Did you add tests to cover your changes (yes/no)?
no. updated existing
### Did you update the documentation accordingly (yes/no)?
yes
### Did you read the CONTRIBUTING document (yes/no)?
yes
### Summary
Changes to file/folder name, class name and file location inside qlibrary.

2021-04-21 19:57 UTC, JeremyDrysdale-ibm requested changes
Overall looks good, nice job.  One typo to fix is noted.

2021-04-21 19:57 UTC, JeremyDrysdale-ibm commented on qiskit_metal/qlibrary/core/base.py
> +    """`QComponent` is the ore class for all Metal components and is the
typo - should say `core` not `ore`

2021-04-21 20:38 UTC, JeremyDrysdale-ibm approved these changes

2021-04-22 22:29 UTC, ThomasGM4 approved these changes
Looks good

2021-04-23 13:50 UTC, merged