545 corner rounding 45 deg
Qiskit/qiskit-metal pull request #599
Opened 2021-06-18 20:26 UTC by dwang429

### What are the issues this pull addresses (issue numbers / links)?
This PR closes issue 545.

### Did you add tests to cover your changes (yes/no)?
No.

### Did you update the documentation accordingly (yes/no)?
Yes.

### Did you read the CONTRIBUTING document (yes/no)?
Yes.

### Summary
This updated fillet code permits fillets at arbitrary rotation angles, not just in increments of 90 deg. See pictures below.

### Details and comments
![45 deg Fillet 250 um](https://user-images.githubusercontent.com/16978018/122612859-b6e2e080-d038-11eb-8aff-d8b3d31afd8b.png)
![45 deg Fillet 150 um](https://user-images.githubusercontent.com/16978018/122612861-b77b7700-d038-11eb-830d-d4747e905aa8.png)
![45 deg Fillet 100 um](https://user-images.githubusercontent.com/16978018/122612862-b8140d80-d038-11eb-995e-ace9ab04fa5f.png)
![45 deg Fillet 50 um](https://user-images.githubusercontent.com/16978018/122612863-b8140d80-d038-11eb-991b-730c0734e0c3.png)
![45 deg Fillet 0 um](https://user-images.githubusercontent.com/16978018/122612865-b8aca400-d038-11eb-8694-4220e15741c5.png)
![45 deg Fillet 200 um](https://user-images.githubusercontent.com/16978018/122612867-b8aca400-d038-11eb-83d2-7911eb15a05e.png)
![90 deg New Fillet Code Test](https://user-images.githubusercontent.com/16978018/122612869-b9453a80-d038-11eb-865d-7ac699745a0c.png)

2021-06-18 21:27 UTC, marcolincs requested changes
All changes are tested and good. need some more work

1. I made a commit to correct something trivial that caused QComponent make() to fail for straight segments (2 points)

2. Side effect: could not correct yet a side effect of `check_length` and `del_colinear_points`. `check_length` does a simple point to point distance check, so it relies on `del_colinear_points` to remove any colinear points. However `del_colinear_points` was designed thinking Manhattan (horizontal and vertical). Therefore: errors on straight segments that are not 90 degrees
![image](https://user-images.githubusercontent.com/25931310/122616662-c70ab800-d058-11eb-8d40-45e68f1ce3b4.png)
these are the points. you can see that cpw1/2 (horizontal and vertical) points were "reduced" when aligned. while cpw3/4 were not reduced.
![image](https://user-images.githubusercontent.com/25931310/122617152-bad32a80-d059-11eb-871e-bb19ffbc98ac.png)

2021-06-18 22:22 UTC, marcolincs submitted a review, later dismissed
I made another commit to resolve the del_colinear_points() limitation for non-90deg

2021-06-18 22:40 UTC, marcolincs approved these changes

2021-06-19 00:25 UTC, zlatko-minev commented
Good checks!

2021-06-21 10:32 UTC, JeremyDrysdale-ibm approved these changes

2021-06-21 14:24 UTC, merged