610 connection pads
Qiskit/qiskit-metal pull request #614
Opened 2021-06-22 16:47 UTC by grace-harper-ibm

### What are the issues this pull addresses (issue numbers / links)?
#610 

### Did you add tests to cover your changes (yes/no)?
no
### Did you update the documentation accordingly (yes/no)?
no
### Did you read the CONTRIBUTING document (yes/no)?
no
### Summary
Param Entry Window now has a default connection pad for qubits to make it easier for users to know how to add connection pads

### Details and comments

2021-06-23 10:29 UTC, JeremyDrysdale-ibm requested changes
Please merge main and resolve the merge conflicts.

2021-06-24 18:00 UTC, grace-harper-ibm commented on qiskit_metal/_gui/widgets/create_component_window/parameter_entry_window.py
> +                '_default_connection_pads': ('connection_pads', {
Do you want all the default options shown? I can do that, but earlier there had been talk that this was too many options for the user to see when they opened the tab.

2021-06-24 18:21 UTC, zlatko-minev commented on qiskit_metal/_gui/widgets/create_component_window/parameter_entry_window.py
> +                '_default_connection_pads': ('connection_pads', {
It's a good question. 
I was thinking here about the fact that in the following code we are presuming to know the keys and values that will necessarily exist for a connection pad dictionary, which may or may not be the same for different qubits. If the component doesn’t use loc_W or loc_H for example, these params would not function. 

I was wondering if we could make it more general, by not restricting the pad keys to ones that the component may have or may not have. 
You're right the tradeoff for this generality would then be to potentially have too many parameters. 
I may in this case lean on the side of having more parameters, just to be more general in this case, and I am open to comments

2021-06-24 22:32 UTC, grace-harper-ibm commented on qiskit_metal/_gui/widgets/create_component_window/parameter_entry_window.py
> +                '_default_connection_pads': ('connection_pads', {
I've updated the code

2021-06-25 10:53 UTC, JeremyDrysdale-ibm approved these changes

2021-06-25 18:29 UTC, zlatko-minev approved these changes
Nice!

2021-06-25 19:15 UTC, merged