Time evolution simulation with Sequencing plus demo tutorial
Qiskit/qiskit-metal pull request #753
Opened 2022-01-21 08:37 UTC by quantum-quant

### What are the issues this pull addresses (issue numbers / links)?
Time evolution simulation with Sequencing plus demo tutorial

### Did you add tests to cover your changes (yes/no)?
no

### Did you update the documentation accordingly (yes/no)?
yes

### Did you read the CONTRIBUTING document (yes/no)?
yes

### Summary

### Details and comments

2022-01-25 19:32 UTC, zlatko-minev requested changes
see class LOMtoSeqMapper comments

2022-01-25 19:32 UTC, zlatko-minev commented on qiskit_metal/analyses/quantization/lom_time_evolution_sim.py
> +            return seq.Cavity
i.e. on the fly so we dont need to hard code it in the code here

2022-01-26 17:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=753) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=753) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-metal?pullRequest=753) it.</sub>

2022-01-26 18:59 UTC, priti-ashvin-shah-ibm commented
> [![CLA assistant check](https://camo.githubusercontent.com/4c970efeed75dd01f6778bf7e33dec85e4171375cb69acb0927bfc9d437d78d9/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=753) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-metal?pullRequest=753) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-metal?pullRequest=753) it.

@quantum-quant , there was an issue with CLA, could you sign it again?

2022-01-31 07:44 UTC, quantum-quant commented on qiskit_metal/analyses/quantization/lom_time_evolution_sim.py
> +    def mapper(metal_system):
fixed based on feedback

2022-01-31 07:44 UTC, quantum-quant commented on qiskit_metal/analyses/quantization/lom_time_evolution_sim.py
> +            return seq.Cavity
fixed based on feedback

2022-02-09 20:53 UTC, zlatko-minev approved these changes

2022-02-09 22:41 UTC, merged