Implement Ability to Extract Q-factors from Eigenmode Simulations
Qiskit/qiskit-metal pull request #789
Opened 2022-04-06 15:35 UTC by SamarthH

### What are the issues this pull addresses (issue numbers / links)?

### Did you add tests to cover your changes (yes/no)?
no
### Did you update the documentation accordingly (yes/no)?
no
### Did you read the CONTRIBUTING document (yes/no)?
yes
### Summary
This pull request implements the ability to render and use resistive ports in Eigenmode simulations in order to find the Q-factors of resonators and to simulate other dissipative effects.

### Details and comments
- Included a variable in QAnsysRenderer when execute_design is called to store the solution type
- After that, when create_ports is called by hfss_renderer, choose to create RLC ports if the solution type is Eigenmode
- Added tutorial to showcase how-to.

2022-04-06 15:38 UTC, SamarthH commented
For some reason, git is not diffing the files properly, and hence the commit looks much much larger than it is. It is just a few lines of code in execute_design and create_ports.

2022-04-19 19:25 UTC, gsteele13 commented
i would love to try this out!

2022-04-21 07:39 UTC, SamarthH commented
Sorry for the delay. I shall also push the extra meshing part in a moment.

2022-04-23 09:21 UTC, SamarthH commented
I think that this is all that I have to implement at the moment. Please review this and let me know of any necessary changes @zlatko-minev @ThomasGM4 . Thanks a lot!

2022-04-25 18:53 UTC, ThomasGM4 commented
Thanks for working on this. Will look through the code shortly, might take a little bit extra just because of the way the diff is for the entire file instead of the code you changed (I am also not sure why it did it like that).

2022-04-25 18:56 UTC, zlatko-minev commented
Ditto @ThomasGM4 , excited to look over, thanks for the contribution work!

2022-04-27 02:19 UTC, ThomasGM4 requested changes
You will want to clear all the outputs for your demo notebook, all the shapely warnings are still present. (4.18 Analyse a Resonator with Ports.ipynb)

Couple comments in the code itself but it looks good (not sure why it did so much line replacement, used BeyondCompare for sanity check, and most the replaced lines was just due to " -> '

2022-04-27 02:19 UTC, ThomasGM4 commented on qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
> +                                                   ymax - ymin, z,
good catch

2022-04-27 16:03 UTC, SamarthH commented on qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
> +
Sorry, I don't know how that happened. Did not intend to do that. Shall add that back

2022-04-27 16:07 UTC, SamarthH commented on qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
> +            else:
There is indeed one possible case, which is to simulate a parallel plate capacitor (like the one used for a lot of lumped element JPA setups).

2022-04-27 16:10 UTC, SamarthH commented on qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
> +                                                   ymax - ymin, z,
Thanks

2022-04-27 18:16 UTC, SamarthH commented on qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
> +
I have re-added the Chalmers comment. Please take a look

2022-05-05 15:05 UTC, ThomasGM4 commented on qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
> +
Sure you can add your name after that line too

2022-05-05 15:11 UTC, ThomasGM4 commented on qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
> +
Looks good to merge after that.

2022-05-06 06:51 UTC, SamarthH commented on qiskit_metal/renderers/renderer_ansys/hfss_renderer.py
> +
Done!

2022-05-08 23:31 UTC, ThomasGM4 approved these changes

2022-05-09 05:33 UTC, SamarthH commented
@ThomasGM4 : Could you please merge the commits into the main branch? Then I would close the pull request.

2022-05-09 19:49 UTC, merged