Double-side loaded transmission line model and multi-node subsystems
Qiskit/qiskit-metal pull request #791
Opened 2022-04-14 00:53 UTC by quantum-quant

### What are the issues this pull addresses (issue numbers / links)?
* Implemented double-side loaded TL resonator model
* New TL model nicely resolves to single-side loaded and/or single-side shorted models under approriate boundary conditions
* Generalize multi-node subsystems which were necessary for the double-sided TL
model

### Did you add tests to cover your changes (yes/no)?
* Checked and verified that the double-side loaded TL model can recover single-side loaded results under approriate bouonary conditions
* Check that new changes do not break existing tutorials/applications

### Did you update the documentation accordingly (yes/no)?
yes

### Did you read the CONTRIBUTING document (yes/no)?
yes

### Summary

### Details and comments

2022-04-14 18:57 UTC, ThomasGM4 commented
I presume want to merge in #790 first?

2022-04-19 17:25 UTC, zlatko-minev requested changes
Add units

2022-04-19 17:25 UTC, zlatko-minev commented on qiskit_metal/analyses/quantization/lom_core_analysis.py
> +    _POS_INFTY = 1e30
What about different systems?

2022-04-25 17:14 UTC, quantum-quant commented on qiskit_metal/analyses/quantization/lom_core_analysis.py
> +                            g[idx1, idx2] = c_i * Q_zpf_1 * Q_zpf_2 * \
added unit comment in docstring

2022-04-25 17:21 UTC, zlatko-minev approved these changes

2022-04-25 17:21 UTC, zlatko-minev commented on qiskit_metal/analyses/quantization/lom_core_analysis.py
> +        Note that the computed g's are in MHz
Nice

2022-04-25 18:09 UTC, merged