856 toolbox metal test cases
Qiskit/qiskit-metal pull request #859
Opened 2022-10-05 20:02 UTC by cdelnano

### What are the issues this pull addresses (issue numbers / links)?
[#856 Add Additional Test Cases](https://github.com/Qiskit/qiskit-metal/issues/856)

### Did you add tests to cover your changes (yes/no)?
yes

### Did you update the documentation accordingly (yes/no)?
no (added comments in test_toolbox_metal.py)

### Did you read the CONTRIBUTING document (yes/no)?
yes

### Summary
Added unit tests for the following functions/methods:
- input_error
- open_docs
- orient_me
- get_platform_info
- extract_value_unit
- aligned_pts

### Details and comments
Added unit tests to validate these functions/methods.

2022-10-07 15:51 UTC, priti-ashvin-shah-ibm approved these changes
This a great start to adding test cases to CI.  Thank you.

2022-10-11 17:30 UTC, ThomasGM4 requested changes

2022-10-11 17:30 UTC, ThomasGM4 commented on qiskit_metal/tests/test_toolbox_metal.py
> +        self.assertEqual(parsing.extract_value_unit("200", "mm"), 200.0)
Think you would want the testing to be something like

`self.assertEqual(parsing.extract_value_unit("200mm", "mm"), 200.0)`

or

`self.assertEqual(parsing.extract_value_unit("200um", "mm"), 0.2)`

2022-10-11 18:04 UTC, obrienpja approved these changes
LGTM! Great job!

2022-10-11 19:46 UTC, cdelnano reviewed
Updated test_toolbox_metal_extract_value_unit per Thomas's comment.

2022-10-11 20:26 UTC, priti-ashvin-shah-ibm approved these changes
LGTM, great job.

2022-10-11 21:05 UTC, ThomasGM4 approved these changes

2022-10-13 15:10 UTC, merged